name: sprite_2_dart
description: A sample command-line application.
version: 1.0.0

environment:
  sdk: ^3.8.0

dependencies:
  http: ^1.6.0

dev_dependencies:
  flutter_lints: ^6.0.0
  test: ^1.24.0
